Repository carthage-software/mago, pull requests merged in 2025-09, with the labels that each got.

#372 chore(nix): add dev flake (rustup: 1.89.0 + nightly) and docs
  .envrc
  .gitignore
  CONTRIBUTING.md
  docs/contributing.md
  flake.lock
  flake.nix
Labels: Priority: Medium, Type: Enhancement, Type: Maintenance

#389 fix(stubs): sizeof return type should be the same as count
  crates/prelude/assets/extensions/standard.php
Labels: Priority: Medium, Type: Enhancement, Status: Closed, Subject: Analyzer

#387 fix(stubs): refine end() return type annotation
  crates/prelude/assets/extensions/standard.php
Labels: Priority: Medium, Type: Enhancement, Status: Closed, Subject: Analyzer

#386 feat(codex): add support for `#[\Deprecated]` on traits
  crates/analyzer/tests/cases/use_inheritance_error_path.php
  crates/codex/src/scanner/class_like.rs
Labels: Priority: Medium, Type: Enhancement, Subject: Analyzer

#408 feat(analyzer): allow lists/arrays of Named Objects to be passed into array_column
  crates/analyzer/src/invocation/special_function_like_handler/mod.rs
  crates/analyzer/src/invocation/special_function_like_handler/standard/array.rs
  crates/analyzer/src/invocation/special_function_like_handler/standard/mod.rs
  crates/analyzer/tests/cases/issue_275.php
  crates/analyzer/tests/mod.rs
  crates/codex/src/ttype/union.rs
  crates/prelude/assets/extensions/standard.php
Labels: Priority: High, Type: Bug, Type: Enhancement, Status: Closed, Subject: Analyzer

#416 fix(analyzer): clone type recognition inside traits
  crates/analyzer/src/expression/clone.rs
  crates/analyzer/tests/cases/issue_415.php
  crates/analyzer/tests/mod.rs
Labels: Priority: High, Type: Bug, Status: Closed, Subject: Analyzer

#434 docs: update link for PHP CodeSniffer
  README.md
Labels: Priority: Low, Type: Maintenance

#438 Include Cargo and Rustc in flake.nix
  flake.nix
Labels: Priority: Medium, Type: Maintenance
