Repository carthage-software/mago, pull requests merged in 2025-04, with the labels that each got.

#176 feat(linter): implement `--mimimum-level` to lint command (#174)
  crates/reporting/src/lib.rs
  src/commands/lint.rs
Labels: Priority: High, Status: Completed, Type: Enhancement, Subject: Linter

#193 fix: support compiling mago-formatter to wasm32-unknown-unknown
  Cargo.lock
  Cargo.toml
  crates/wasm/Cargo.toml
Labels: Priority: Critical, Status: Review Needed, Type: Maintenance, Subject: Formatter

#194 chores(doc): Added Helix instructions to configure Mago
  docs/recipes/editor-integration.md
  docs/recipes/editor-integration/helix.md
Labels: Priority: Medium, Status: Accepted, Type: Documentation, Subject: Formatter
